Start testing: Oct 26 17:40 CEST
----------------------------------------------------------
1/1 Testing: TestBiblioteki1
1/1 Test: TestBiblioteki1
Command: "/home/student/Pulpit/224247/trunk/projekt/biblioteka/TestBibl" "--report_level=detailed" "--log_level=all" "--color_output=yes"
Directory: /home/student/Pulpit/224247/trunk/projekt/biblioteka
"TestBiblioteki1" start time: Oct 26 17:40 CEST
Output:
----------------------------------------------------------
Running 1 test case...
[1;34;49mEntering test module "Master Test Suite"
[0;39;49m[1;34;49m/home/student/Pulpit/224247/trunk/projekt/biblioteka/test/ClientTest.cpp(5): Entering test suite "ClientSuiteCorrect"
[0;39;49m[1;34;49m/home/student/Pulpit/224247/trunk/projekt/biblioteka/test/ClientTest.cpp(7): Entering test case "ClientFirstNameCase"
[0;39;49m/home/student/Pulpit/224247/trunk/projekt/biblioteka/test/ClientTest.cpp(9): [1;32;49minfo: check client.getFirstName() == "Jan" has passed[0;39;49m
/home/student/Pulpit/224247/trunk/projekt/biblioteka/test/ClientTest.cpp(10): [1;32;49minfo: check client.getLastName() == "Kowalski" has passed[0;39;49m
/home/student/Pulpit/224247/trunk/projekt/biblioteka/test/ClientTest.cpp(11): [4;31;49mfatal error: in "ClientSuiteCorrect/ClientFirstNameCase": critical check client.getPersonalID() == "Jan" has failed [Kowalski != Jan][0;39;49m
Wywolano destruktor
[1;34;49m/home/student/Pulpit/224247/trunk/projekt/biblioteka/test/ClientTest.cpp(7): Leaving test case "ClientFirstNameCase"; testing time: 170us
[0;39;49m[1;34;49m/home/student/Pulpit/224247/trunk/projekt/biblioteka/test/ClientTest.cpp(5): Leaving test suite "ClientSuiteCorrect"; testing time: 183us
[0;39;49m[1;34;49mLeaving test module "Master Test Suite"; testing time: 194us
[0;39;49m
Test module "Master Test Suite" has failed with:
  1 test case out of 1 failed
  1 test case out of 1 aborted
  2 assertions out of 3 passed
  1 assertion out of 3 failed

  Test suite "ClientSuiteCorrect" has failed with:
    1 test case out of 1 failed
    1 test case out of 1 aborted
    2 assertions out of 3 passed
    1 assertion out of 3 failed

    Test case "ClientSuiteCorrect/ClientFirstNameCase" was aborted with:
      2 assertions out of 3 passed
      1 assertion out of 3 failed

<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"TestBiblioteki1" end time: Oct 26 17:40 CEST
"TestBiblioteki1" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Oct 26 17:40 CEST
